#!/bin/python3

input=[int(x) for x in input().split()]


if (input[1]-input[3]) !=0:
    m = ((input[2] - input[0]) / (input[1] - input[3]))
    if m%1==0 and m>=0:
        print("YES")
    else:
        print("NO")
else:
    if input[0]==input[2]:
        print("YES")
    else:
        print("NO")
