#!/bin/python3

n=int(input())
array=[int(x) for x in input().split()]


len=len(array)
pos=0
neg=0
zer=0
for i in array:
    if i>0:
        pos+=1
    elif i<0:
        neg+=1
    elif i==0:
        zer+=1

print(pos/len)
print(neg/len)
print(zer/len)
