#!/bin/python3

n=int(input())
i=1
while i<=n:
    #print(f"loop1 {i}")
    j=1
    while j<=n-i:
        print(" ", end='')
        j+=1
        #print(f"loop2 {j}")
    k=1
    while k<=i:
        print("#",end='')
        k+=1
        #print("loop3")
    print()
    i+=1

